name: HelloWorldPlugin
main: com.deax.dev.kotlingradle.MainPlugin
version: 0.1
author: DeaX
description: Самый глупый плагин
commands:
  #echo:
  #  usage: '/echo Hello world'
  #  description: 'Says your arguments'
  setcompas:
    usage: |-
      /setcompas x z
      or
      /setcompas clear
    description: 'Navigate compas for your coordinates or clear to spawn'